# Generated by Django 5.2.4 on 2025-08-02 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BargainRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('requested_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_offer', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('countered', 'Countered'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bargain_requests', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bargain_requests', to='products.product')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_bargains', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('buyer', 'product', 'status')},
            },
        ),
        migrations.CreateModel(
            name='BargainMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('offered_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_counter_offer', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('bargain_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='bargaining.bargainrequest')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='BargainSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_auto_accept', models.BooleanField(default=False)),
                ('auto_accept_threshold', models.DecimalField(blank=True, decimal_places=2, help_text='Auto-accept if discount is less than this percentage', max_digits=5, null=True)),
                ('enable_auto_reject', models.BooleanField(default=False)),
                ('auto_reject_threshold', models.DecimalField(blank=True, decimal_places=2, help_text='Auto-reject if discount is more than this percentage', max_digits=5, null=True)),
                ('default_response_time_hours', models.PositiveIntegerField(default=24)),
                ('enable_auto_counter', models.BooleanField(default=False)),
                ('counter_offer_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Automatically counter with this percentage discount', max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bargain_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
