# Generated by Django 5.1 on 2025-08-02 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bargaining', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bargainrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('countered', 'Countered'), ('expired', 'Expired'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
