# Generated by Django 5.1 on 2025-08-03 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bargaining', '0002_alter_bargainrequest_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bargainrequest',
            unique_together=set(),
        ),
    ]
