# Generated by Django 5.1 on 2025-08-03 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('crazycart_wallet', 'CrazyCart Wallet'), ('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('bkash', 'bKash'), ('bank_transfer', 'Bank Transfer'), ('cash_on_delivery', 'Cash on Delivery'), ('upi', 'UPI')], max_length=20),
        ),
    ]
