# Generated by Django 5.2.4 on 2025-08-03 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='durum',
            field=models.BooleanField(default=True),
        ),
    ]
