# Generated by Django 5.2.4 on 2025-08-03 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_durum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='durum',
        ),
    ]
